### ISSUE TITLE
Gem5 to McPat

### ISSUE THREAD

**Issue by jrpdn** [Hardik44/Gem5toMcPat_parser#2]
Hi,
I have the following error while executing the given parser. the error is

Traceback (most recent call last):
  File "Program.py", line 964, in <module>
    main()
  File "Program.py", line 45, in main
    readWriteConfigValue(sys.argv[2])
  File "Program.py", line 501, in readWriteConfigValue
    foundVal = getConfValue(mapping[name])                  #Get value from config file
  File "Program.py", line 589, in getConfValue
    currentConfig = currentConfig["cpu"][int(coreNo)]
ValueError: invalid literal for int() with base 10: '_clk_domain'

the gem5 simulation is,
./build/NULL/gem5.opt configs/example/garnet_synth_traffic.py \
--network=garnet2.0 \
--num-cpus=16 \
--num-dirs=16 \
--topology=Mesh_XY \
--mesh-rows=4 \
--sim-cycles=1000 \
--injectionrate=0.9 \
--synthetic=uniform_random

Thanks and best regards

**Comment by waikin-ng** [comment]
Block size must >= 1

Hi.
I am seeing error above when running ./mcpat -infile config.xml -print_level 5 -opt_for_clk 1 > mcpatoutput.

Can you please comment on what I am missing here?

Thanks and regards.
